export enum TipoEventoBitacora {
  LOGIN_EXITOSO = 'LOGIN_EXITOSO',
  LOGIN_FALLIDO_USUARIO = 'LOGIN_FALLIDO_USUARIO',
  LOGIN_FALLIDO_CONTRASENA = 'LOGIN_FALLIDO_CONTRASENA',
  LOGIN_BLOQUEADO = 'LOGIN_BLOQUEADO',
  CUENTA_BLOQUEADA = 'CUENTA_BLOQUEADA',
  LOGOUT = 'LOGOUT',
}
